	<footer class="footer container mb--md" id="footer">
		<div class="footer__box">
			<div class="footer__logo">

				<a href="#"><img src="<?php echo get_theme_file_uri('/images/logo4.svg') ?>" alt="logo firmy" /></a>
			</div>
			<ul class="footer__icons">
				<li class="footer__icon">
					<a href="https://www.facebook.com/SchodyZalinski" target="_blank" rel="noopener" class="footer__link">
						<!-- Generated by IcoMoon.io -->
						<svg class="icon footer--icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
							<title>facebook</title>
							<path d="M29 0h-26c-1.65 0-3 1.35-3 3v26c0 1.65 1.35 3 3 3h13v-14h-4v-4h4v-2c0-3.306 2.694-6 6-6h4v4h-4c-1.1 0-2 0.9-2 2v2h6l-1 4h-5v14h9c1.65 0 3-1.35 3-3v-26c0-1.65-1.35-3-3-3z"></path>
						</svg>
					</a>
				</li>
				<li class="footer__icon">
					<a href="https://goo.gl/maps/BQoUo2vP6ZzJmXqq9" target="_blank" rel="noopener" class="footer__link">
						<!-- Generated by IcoMoon.io -->
						<svg class="icon footer--icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
							<title>location</title>
							<path d="M16 0c-5.523 0-10 4.477-10 10 0 10 10 22 10 22s10-12 10-22c0-5.523-4.477-10-10-10zM16 16c-3.314 0-6-2.686-6-6s2.686-6 6-6 6 2.686 6 6-2.686 6-6 6z"></path>
						</svg>
					</a>
				</li>
				<li class="footer__icon">
					<a href="mailto:staszekzalinski30@interia.pl" target="_self" class="footer__link">
						<!-- Generated by IcoMoon.io -->
						<svg class="icon footer--icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
							<title>envelop</title>
							<path d="M29 4h-26c-1.65 0-3 1.35-3 3v20c0 1.65 1.35 3 3 3h26c1.65 0 3-1.35 3-3v-20c0-1.65-1.35-3-3-3zM12.461 17.199l-8.461 6.59v-15.676l8.461 9.086zM5.512 8h20.976l-10.488 7.875-10.488-7.875zM12.79 17.553l3.21 3.447 3.21-3.447 6.58 8.447h-19.579l6.58-8.447zM19.539 17.199l8.461-9.086v15.676l-8.461-6.59z"></path>
						</svg>
					</a>
				</li>
				<li class="footer__icon">
					<a href="tel:+48881359571" class="footer__link">
						<!-- Generated by IcoMoon.io -->
						<svg class="icon footer--icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
							<title>phone</title>
							<path d="M22 20c-2 2-2 4-4 4s-4-2-6-4-4-4-4-6 2-2 4-4-4-8-6-8-6 6-6 6c0 4 4.109 12.109 8 16s12 8 16 8c0 0 6-4 6-6s-6-8-8-6z"></path>
						</svg>
					</a>
				</li>
			</ul>
			<p class="footer__copyright">
				© <span class="year">2021</span> Created by gregsypek
			</p>
		</div>

		<div class="footer__address">
			<p class="footer__heading mb--md">Kontakt</p>
			<address class="footer__address">
				<p>Stanisław Zaliński</p>
				<p>Trzciana 488C</p>
				<p>39-304 Czermin</p>
				<p>tel: 881 359 571</p>
			</address>
		</div>
		<div class="footer__nav">
			<p class="footer__heading mb--md">Informacje</p>
			<ul class="footer__links">
				<li><a href="<?php echo site_url('/home') ?>" class="footer__link">O nas</a></li>
				<li><a href="<?php echo site_url('/oferta') ?>" class="footer__link">Oferta</a></li>
				<li><a href="<?php echo site_url('/cennik') ?>" class="footer__link">Cennik</a></li>
			</ul>
		</div>
	</footer>

	<?php wp_footer(); ?>
	</body>

	</html>