<?php get_header(); ?>



<main>
  <section id="hero" class="section-hero padding--verticall">
    <div class="hero container">
      <div class="hero__text-box mb--md">
        <h1 class="heading-primary mb--bg">
          Robimy <span>schody</span>, które wyglądają świetnie i zachwycają
          jakością.
        </h1>
        <a href="#about" class="btn btn--full">Więcej</a>
      </div>
      <div class="hero__img-box">
        <picture>
          <source srcset="<?php echo get_theme_file_uri('/images/hero.webp') ?>" type="image/webp" />
          <source srcset="<?php echo get_theme_file_uri('/images/hero.png') ?>" type="image/png" />
          <img src=" <?php echo get_theme_file_uri('/images/hero.png') ?>" alt="Schody drewniane na betonie, Kolejne schody jako przykładowa praca" class="hero__img" width="40vw" height="auto" />
        </picture>
      </div>
    </div>
  </section>
  <section id="quality" class="quality">
    <div class="container padding--big">
      <div class="top">
        <h2 class="heading-secondary">Wybierz <span>jakość</span></h2>

        <h3 class="quality__description description">
          Jako zgrany zespół specjalistów wykonujemy usługi stolarskie na
          najwyższym poziomie. Uważamy że każdy detal powinien być
          dopracowany. Oto co nas wyróżnia i sprawia że klienci są zadowleni
          i chętnie nas polecają.
        </h3>
      </div>
      <div class="quality__bottom">
        <div class="quality__cards">
          <div class="quality__card">
            <!-- Generated by IcoMoon.io -->
            <svg class="card-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
              <title>check-alt</title>
              <path d="M16 0c-8.836 0-16 7.164-16 16s7.164 16 16 16 16-7.164 16-16-7.164-16-16-16zM13.52 23.383l-7.362-7.363 2.828-2.828 4.533 4.535 9.617-9.617 2.828 2.828-12.444 12.445z"></path>
            </svg>

            <!-- <ion-icon class="card-icon" name="checkmark-circle"></ion-icon class="card-icon"> -->
            <p class="quality__card-description">
              Profesjonalne podejście do każdego klenta
            </p>
          </div>
          <div class="quality__card">
            <!-- Generated by IcoMoon.io -->
            <svg class="card-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
              <title>calendar-alt-fill</title>
              <path d="M26 4v2.047c0 2.211-1.789 4-4 4s-4-1.789-4-4v-2.047h-4v2.047c0 2.211-1.789 4-4 4s-4-1.789-4-4v-2.047h-6v28h32v-28h-6zM10 28h-4v-4h4v4zM10 20h-4v-4h4v4zM18 28h-4v-4h4v4zM18 20h-4v-4h4v4zM22 28v-4h4l-4 4zM26 20h-4v-4h4v4zM8 6v-4c0-1.105 0.895-2 2-2s2 0.895 2 2v4c0 1.105-0.895 2-2 2s-2-0.895-2-2zM20 6v-4c0-1.105 0.895-2 2-2s2 0.895 2 2v4c0 1.105-0.895 2-2 2s-2-0.895-2-2z"></path>
            </svg>


            <p class="quality__card-description">Szybki czas realizacji</p>
          </div>
          <div class="quality__card">
            <!-- Generated by IcoMoon.io -->
            <svg class="card-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
              <title>trophy</title>
              <path d="M26 6v-4h-20v4h-6v4c0 3.314 2.686 6 6 6 0.627 0 1.232-0.096 1.801-0.275 1.443 2.063 3.644 3.556 6.199 4.075v6.2h-2c-2.209 0-4 1.791-4 4h16c0-2.209-1.791-4-4-4h-2v-6.2c2.555-0.519 4.756-2.012 6.199-4.075 0.568 0.179 1.173 0.275 1.801 0.275 3.314 0 6-2.686 6-6v-4h-6zM6 13.625c-1.999 0-3.625-1.626-3.625-3.625v-2h3.625v2c0 1.256 0.232 2.457 0.655 3.565-0.213 0.039-0.431 0.060-0.655 0.060zM29.625 10c0 1.999-1.626 3.625-3.625 3.625-0.224 0-0.442-0.021-0.655-0.060 0.423-1.107 0.655-2.309 0.655-3.565v-2h3.625v2z"></path>
            </svg>

            <p class="quality__card-description">
              Jakość na pierwszym miejscu
            </p>
          </div>
          <div class="quality__card">
            <!-- Generated by IcoMoon.io -->
            <svg class="card-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
              <title>heart</title>
              <path d="M23.6 2c-3.363 0-6.258 2.736-7.599 5.594-1.342-2.858-4.237-5.594-7.601-5.594-4.637 0-8.4 3.764-8.4 8.401 0 9.433 9.516 11.906 16.001 21.232 6.13-9.268 15.999-12.1 15.999-21.232 0-4.637-3.763-8.401-8.4-8.401z"></path>
            </svg>

            <p class="quality__card-description">
              Pasja poparta doświadczeniem
            </p>
          </div>
        </div>
      </div>
      <div class="quality__btn">
        <a href="<?php echo site_url('/oferta') ?>" class="btn btn--quality">Nasza oferta</a>
      </div>
    </div>
  </section>
  <section id="about" class="about padding--big container">
    <h2 class="heading-secondary mb--bg">Kim <span>jesteśmy</span></h2>
    <div class="about__box">
      <div class="about__description mb--bg">
        <p class="description">
          Nasza firma powstałą w 2011 roku, a więc już ponad 10 lat temu.
          Specjalizujemy się w produkcji schodów drewnianych głównie na
          terenach południowej Polski.
        </p>

        <p class="description">
          Wykonujemy kilka par schodów miesięcznie, więc mamy spore
          doświadczenie w tym co robimy, a nasz niezmienny od lat zespół
          fachowców jest gwarantem dobrze wykonanej pracy.
        </p>
        <p class="description">
          Do produkcji schodów używamy tylko najwyższej jakości drewna, a na
          nasze wyróby udzielamy kilkuletniej gwarancji.
        </p>
      </div>

      <picture>

        <source srcset="<?php echo get_theme_file_uri('/images/about.webp') ?>" type="image/webp" />
        <source srcset="i<?php echo get_theme_file_uri('/images/about.jpg') ?>" type="image/jpg" />
        <img class="about__photo" src="<?php echo get_theme_file_uri('/images/about.webp') ?>" alt="Pracownik szlifuje drewno" width="400" height="400" />
      </picture>
    </div>
  </section>
</main>
<?php get_footer();

?>