<!DOCTYPE html>
<html <?php language_attributes(); ?>>

<head>
  <meta charset="<?php bloginfo('charset'); ?>">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="Wykonujemy schody drewniane różnego rodzaju z wykorzystaniem najwzszej jakości drewna, głównie dąb." />

  <link rel="icon" href="<?php echo get_theme_file_uri('/images/favicon.png') ?>" />

  <link rel="apple-touch-icon" href="<?php echo get_theme_file_uri('/images/apple-touch-icon.png') ?>" />
  <link rel="manifest" href="manifest.webmanifest" />
  <link rel="preconnect" href="https://fonts.gstatic.com" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <?php wp_head(); ?>
</head>

<body <?php body_class(); ?>>
  <header class="header">
    <a href="<?php echo site_url('/home') ?>">

      <img class="logo" src="<?php echo get_theme_file_uri('/images/logo4.svg') ?>" alt="Usługi Stolarskie logo" /></a>
    <nav class="main__nav">
      <ul class="main__list">
        <li <?php if (is_page('home')) echo 'class="active"' ?>><a href="<?php echo site_url('/') ?>" class="main__link active"> Strona główna</a></li>
        <li <?php if (get_post_type() == 'post') echo 'class="active"' ?>><a href="<?php echo site_url('/oferta') ?>" class="main__link"> Oferta</a></li>
        <li <?php if (is_page('cennik')) echo 'class="active"' ?>><a href="<?php echo site_url('/cennik') ?>" class="main__link"> Cennik</a></li>
        <li <?php if (is_page('kontakt')) echo 'class="active"' ?>><a href="<?php echo site_url('/kontakt') ?>" class="main__link"> Kontakt</a></li>
      </ul>
    </nav>
    <button class="btn--mobile-nav">
      <!-- Generated by IcoMoon.io -->
      <svg class="icon--mobile-nav" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>menu</title>
        <path d="M2 6h28v6h-28zM2 14h28v6h-28zM2 22h28v6h-28z"></path>
      </svg>
      <!-- Generated by IcoMoon.io -->
      <svg class="icon--mobile-close" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
        <title>cross</title>
        <path d="M31.708 25.708c-0-0-0-0-0-0l-9.708-9.708 9.708-9.708c0-0 0-0 0-0 0.105-0.105 0.18-0.227 0.229-0.357 0.133-0.356 0.057-0.771-0.229-1.057l-4.586-4.586c-0.286-0.286-0.702-0.361-1.057-0.229-0.13 0.048-0.252 0.124-0.357 0.228 0 0-0 0-0 0l-9.708 9.708-9.708-9.708c-0-0-0-0-0-0-0.105-0.104-0.227-0.18-0.357-0.228-0.356-0.133-0.771-0.057-1.057 0.229l-4.586 4.586c-0.286 0.286-0.361 0.702-0.229 1.057 0.049 0.13 0.124 0.252 0.229 0.357 0 0 0 0 0 0l9.708 9.708-9.708 9.708c-0 0-0 0-0 0-0.104 0.105-0.18 0.227-0.229 0.357-0.133 0.355-0.057 0.771 0.229 1.057l4.586 4.586c0.286 0.286 0.702 0.361 1.057 0.229 0.13-0.049 0.252-0.124 0.357-0.229 0-0 0-0 0-0l9.708-9.708 9.708 9.708c0 0 0 0 0 0 0.105 0.105 0.227 0.18 0.357 0.229 0.356 0.133 0.771 0.057 1.057-0.229l4.586-4.586c0.286-0.286 0.362-0.702 0.229-1.057-0.049-0.13-0.124-0.252-0.229-0.357z"></path>
      </svg>
    </button>
  </header>