<?php

get_header();
?>

<main>
  <section id="contact" class="contact">
    <div class="top padding--big container mb--md">
      <h2 class="heading-secondary">Nasze dane<span>kontaktowe</span></h2>
      <h3 class="contact__description description">
        <?php the_content(); ?>
      </h3>
    </div>
    <div class="contact__bottom container--big">

      <div class="contact__row mb--bg">
        <div class="contact__tab">
          <!-- Generated by IcoMoon.io -->
          <svg class="contact-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
            <title>phone</title>
            <path d="M22 20c-2 2-2 4-4 4s-4-2-6-4-4-4-4-6 2-2 4-4-4-8-6-8-6 6-6 6c0 4 4.109 12.109 8 16s12 8 16 8c0 0 6-4 6-6s-6-8-8-6z"></path>
          </svg>
        </div>
        <div class="contact__card">
          <p class="phone">+48 <?php the_field('telefon') ?></p>
          <p class="email"><?php the_field('email') ?></p>
        </div>
      </div>
      <div class="contact__row mb--bg">
        <div class="contact__card">
          <p class="name"><?php the_field('nazwa_firmy') ?></p>
          <p class="address">
            <?php the_field('adres') ?>
          <p><?php the_field('kod_pocztowy') ?></p>
          </p>
        </div>
        <div class="contact__tab">
          <!-- Generated by IcoMoon.io -->
          <svg class="contact-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
            <title>envelop</title>
            <path d="M29 4h-26c-1.65 0-3 1.35-3 3v20c0 1.65 1.35 3 3 3h26c1.65 0 3-1.35 3-3v-20c0-1.65-1.35-3-3-3zM12.461 17.199l-8.461 6.59v-15.676l8.461 9.086zM5.512 8h20.976l-10.488 7.875-10.488-7.875zM12.79 17.553l3.21 3.447 3.21-3.447 6.58 8.447h-19.579l6.58-8.447zM19.539 17.199l8.461-9.086v15.676l-8.461-6.59z"></path>
          </svg>
        </div>
      </div>
      <div class="contact__row mb--bg">
        <div class="contact__tab">
          <!-- Generated by IcoMoon.io -->
          <svg class="contact-icon" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
            <title>location</title>
            <path d="M16 0c-5.523 0-10 4.477-10 10 0 10 10 22 10 22s10-12 10-22c0-5.523-4.477-10-10-10zM16 16c-3.314 0-6-2.686-6-6s2.686-6 6-6 6 2.686 6 6-2.686 6-6 6z"></path>
          </svg>
        </div>
      </div>
    </div>
  </section>
  <section id="map">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2547.7008243149853!2d21.333124415717005!3d50.31617497945707!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x473d69f5e7dbd781%3A0xc1b2b292b7d6ff28!2sUs%C5%82ugi%20Stolarskie%20Stanis%C5%82aw%20Zali%C5%84ski%20-%20Schody%20drewniane%20-%20Domki%20do%20apiterapii!5e0!3m2!1spl!2spl!4v1629911626622!5m2!1spl!2spl" width="100%" height="100%" style="border: 0" allowfullscreen="" loading="lazy"></iframe>
  </section>
</main>

<?php
get_footer();
?>