<?php

get_header();
?>
<main>
  <section id="price" class="price">
    <div class="price__top top padding--big container mb--md">
      <h2 class="heading-secondary">Nasze oferta<span>cenowa</span></h2>
      <h3 class="price__description description">
        <?php while (have_posts()) {
          the_post();
          the_content();
        } ?>
      </h3>
    </div>
    <div class="price__bottom container--big">

      <?php $cennik = new WP_Query(array(
        'posts_per_page' => -1,
        'post_type' => 'cennik',
        'orderby' => 'post_date'

      ));
      while ($cennik->have_posts()) {
        $cennik->the_post(); ?>

        <div class="price__row row--1">
          <div class="price__col col--1">
            <div class="price__box">
              <img src="<?php the_post_thumbnail_url(); ?>" alt="<?php the_title(); ?>" class="price__photo" />
              <p class="price__title"><?php the_title(); ?></p>
            </div>
          </div>
          <div class="price__col col--2">
            <div class="price__card">
              <p class="price__card-heading">Cena netto</p>
              <div class="price__card-box">
                <sup>od</sup>
                <span class="price__card-value">
                  <?php the_field('cena') ?>
                </span>
                <sub>zł</sub>
              </div>
            </div>
          </div>
          <div class="price__col col--3">
            <div class="price__lists">
              <div class="price__list">
                <header>Cena obejmuje</header>
                <ul class="price__includes">
                  <?php the_field('cena_obejmuje') ?>

                </ul>
              </div>
              <div class="price__list">
                <?php
                $isAddition = get_field('opcje_dodatkowe');
                if ($isAddition) { ?>
                  <header>Opcje dodatkowe</header>
                  <ul class=price__addition">
                    <?php the_field('opcje_dodatkowe') ?>
                  </ul>

                <?php } ?>



              </div>
            </div>
          </div>
        </div>
      <?php }
      wp_reset_postdata();
      ?>
    </div>


  </section>
  <section class="how container padding--huge">
    <div class="bg--center"></div>
    <h2 class="heading-secondary padding--small">Jak uzyskać wycenę<span> cenową?</span></h2>
    <div class="how__cards padding--small">

      <div class="how__card">
        <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>phone</title>
          <path d="M22 20c-2 2-2 4-4 4s-4-2-6-4-4-4-4-6 2-2 4-4-4-8-6-8-6 6-6 6c0 4 4.109 12.109 8 16s12 8 16 8c0 0 6-4 6-6s-6-8-8-6z">
          </path>
        </svg>
        <p class="info">zadzwonić lub wysłać emaila</p>
      </div>
      <div class="how__card">
        <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>phone</title>
          <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>location</title>
            <path d="M16 0c-5.523 0-10 4.477-10 10 0 10 10 22 10 22s10-12 10-22c0-5.523-4.477-10-10-10zM16 16c-3.314 0-6-2.686-6-6s2.686-6 6-6 6 2.686 6 6-2.686 6-6 6z">
            </path>
          </svg>
        </svg>
        <p class="info">podać lokalizację montażu</p>
      </div>
      <div class="how__card">
        <!-- Generated by IcoMoon.io -->
        <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>camera</title>
          <path d="M9.5 19c0 3.59 2.91 6.5 6.5 6.5s6.5-2.91 6.5-6.5-2.91-6.5-6.5-6.5-6.5 2.91-6.5 6.5zM30 8h-7c-0.5-2-1-4-3-4h-8c-2 0-2.5 2-3 4h-7c-1.1 0-2 0.9-2 2v18c0 1.1 0.9 2 2 2h28c1.1 0 2-0.9 2-2v-18c0-1.1-0.9-2-2-2zM16 27.875c-4.902 0-8.875-3.973-8.875-8.875s3.973-8.875 8.875-8.875c4.902 0 8.875 3.973 8.875 8.875s-3.973 8.875-8.875 8.875zM30 14h-4v-2h4v2z">
          </path>
        </svg>

        <p class="info">zrobić kilka zdjęć schodów</p>
      </div>
      <div class="how__card">
        <!-- Generated by IcoMoon.io -->
        <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>shrink2</title>
          <path d="M14 18v13l-5-5-6 6-3-3 6-6-5-5zM32 3l-6 6 5 5h-13v-13l5 5 6-6z"></path>
        </svg>

        <p class="info">określić wzór balustrady</p>
      </div>
      <div class="how__card">
        <!-- Generated by IcoMoon.io -->
        <svg class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
          <title>insert-template</title>
          <path d="M12 6h4v2h-4zM18 6h4v2h-4zM28 6v8h-6v-2h4v-4h-2v-2zM10 12h4v2h-4zM16 12h4v2h-4zM6 8v4h2v2h-4v-8h6v2zM12 18h4v2h-4zM18 18h4v2h-4zM28 18v8h-6v-2h4v-4h-2v-2zM10 24h4v2h-4zM16 24h4v2h-4zM6 20v4h2v2h-4v-8h6v2zM30 2h-28v28h28v-28zM32 0v0 32h-32v-32h32z">
          </path>
        </svg>

        <p class="info">przesłać zrzuty architektoniczne</p>
      </div>
    </div>
  </section>
</main>
<?php
get_footer();
?>